[uwsgi]
module = wsgi:app
home = /app/venv
uid = www-data
gid = www-data

socket = 127.0.0.1:5000
socket = /tmp/uwsgi.sock

chown-socket = www-data:www-data
chmod-socket = 664

master = True
processes = 4
threads = 2

buffer-size=1000000
vacuum = True
die-on-term = True

need-app = true

pythonpath = %(chdir)
pythonpath = /app/venv/lib/python3.8/site-packages
